### ISSUE TITLE
Job page keeps showing "Running..."

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#26]
A page refresh is required to get up to date information. I only noticed this behavior today, using the Nordic+ test server. During previous tests it worked fine.

**Comment by josteinaj** [comment]
I thought I had an issue for this already but apparently not. Thanks!

I'm not sure why this happens. Sometimes a refresh is needed, sometimes it's not. It's weird and I plan to fix it somehow - it's an annoying bug.

**Comment by josteinaj** [comment]
The code for the job view page has been changed a lot since the version where this was an issue.

@bertfrees I'm thinking we can close this issue after a couple of months if nobody reports this issue occuring anymore. Maybe after a couple of months ask our users if they have had this issue lately.

Leaving the issue open for now but moving it to the backlog.

**Comment by bertfrees** [comment]
OK

**Comment by josteinaj** [comment]
@bertfrees have you noticed this issue lately? having to refresh the job view for the page to change from running to done? Or can we close this?

**Comment by bertfrees** [comment]
I haven't seen it anymore myself.
