### ISSUE TITLE
Proper support for regex data type

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-webui#75]
There is no special widget yet for strings that need to match a regular expression, and when submitting a job with an invalid option you just get a generic message "An error occured when trying to post job".

**Comment by bertfrees** [comment]
Hmm, actually the reason I got the message "An error occured when trying to post job" is because I set a required option to the empty string. When I set the option to a non-empty string but invalid according to the regex the job runs fine, because data type validation is not implemented in the engine of course.

**Comment by josteinaj** [comment]
Yeah I was about to ask that. The reason would be that empty strings are interpreted as "unset" options, i.e. they are not sent to the engine, and the engine is expected to use the default value defined in the script instead.

I've changed this in my lates local version though, so that you can send empty strings as options. The downside is that it's impossible to "not give" an option, but I think that's fine, especially now that we have support for default values.

**Comment by josteinaj** [comment]
fixed, but also created #77 which would be an improvement
